url: https://sevcik.dev/
name: Sevcik.dev
description: "Ondrej Sevcik's Portfolio"
plugins: [jekyll-paginate-v2, jekyll-compress-images, jekyll-responsive-image, jekyll-sitemap]
excerpt_separator: <!--more-->
permalink: /:title
highlighter: rouge

collections:
  category:
    output: true

url: "https://sevcik.dev" # the base hostname & protocol for your site

defaults:
  - scope:
      path: "/assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: category
    values:
      layout: "category"

exclude:
  - _compress_images_cache.yml
    
sass:
  style: compressed

  # Responsive images
responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 20 # lq
      quality: 10
    - width: 90 # lq
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 85

  # [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets/img

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/images/resized/%{width}/%{basename}

  # [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  #save_to_source: false

  # [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %} 
  # tags. See the "Caching" section of the README for more information.
  cache: true

  #/ [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # # images. This is useful for resizing images which will be referenced from stylesheets.
  # extra_images:
  #   - assets/foo/bar.png
  #   - assets/bgs/*.png
  #   - assets/avatars/*.{jpeg,jpg}

